is_enabled: true
prefixes:
- "!"
debug: true

femur_breaker_activated_hint: "The Femur Breaker has already been activated."
scp_106_not_alive_hint: "SCP-106 is not out of containment."
audio_file_path: "C:\\Users\\Administrator\\AppData\\Roaming\\EXILED\\Configs\\FemurBreakerSound.ogg"
fake_player_name: "Femur Breaker"
game_object_name: "FemurBrakerButton"
